branch-defaults:
  default:
    environment: dev-env
    group_suffix: null
  master:
    environment: dev-env
global:
  application_name: Desktop
  branch: null
  default_ec2_keyname: null
  default_platform: PHP
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
